pub mod adapter;
pub mod amp_compat;
pub mod auth;
pub mod codex_catalog;
pub mod error;
pub mod failure_capture;
pub mod hot_config;
pub mod model_alias;
pub mod rate_limit;
pub mod route;
pub mod router;
pub mod sse;
pub mod state;
pub mod upstream;
pub mod upstream_response;

pub use error::{AppError, AppResult};
pub use router::build_router;
pub use state::{AppState, RuntimeConfig};
pub use upstream_response::UpstreamResponse;
